import i18n from "i18next";
import { initReactI18next } from "react-i18next";
import type { Locale } from "../domain/models";

const sv = {
  nav: { today: "Idag", log: "Logg", learn: "Träna", journey: "Resan", profile: "Profil" },
  common: { save: "Spara", cancel: "Avbryt", close: "Stäng", add: "Lägg till", done: "Klart", undo: "Ångra", now: "Nu", outside: "Ute", inside: "Inne", nothing: "Inget ännu", today: "Idag", allDogs: "Alla hundar", on: "På", off: "Av", select: "Välj" },
  today: { eyebrow: "En lugnare dag med", next: "Nästa förslag", inAbout: "om", reminderOnBody: "Puppysteps visar nästa lugna förslag när det behövs.", reason: "Varför just nu?", log: "Logga snabbt", routine: "Rutin", routineSaved: "{{activity}} sparades", saveError: "Det gick inte att spara. Försök igen.", wake: "Vaknade", meal: "Åt", play: "Lek", walk: "Promenad", drink: "Drack", sleep: "Sov", ageMonths: "{{count}} månader", noReminder: "Ingen påminnelse ännu", noReminderBody: "Slå på notiser när du är redo – du kan ändra när som helst.", enable: "Visa min rutin", agenda: "Dagens hundar", last: "Senaste händelser", responsible: "Jag ansvarar nu", away: "Jag är inte ansvarig just nu", age: "Åldersanpassad starttid", tip: "Belöna lugnt direkt ute.", subtle: "Följ nästa lilla steg och låt olyckor vara neutrala." },
  weather: { title: "Promenadväder idag", loading: "Hämtar väder…", unavailable: "Väder väntar", refresh: "Uppdatera", now: "Nu", good: "Bra promenad", short: "Kort runda", wait: "Vänta lite", clear: "Klart", mostlyClear: "Mest klart", cloudy: "Molnigt", foggy: "Dimma", rainy: "Regn", snowy: "Snö", showers: "Skurar", snowShowers: "Snöskurar", thunderstorms: "Åska", permission: "Tillåt platsåtkomst för lokalt väder.", error: "Vädret kunde inte hämtas. Försök igen.", source: "Väderdata från Open-Meteo" },
  routine: { wake: "Vakna", meal: "Äta", drink: "Dricka", play: "Lek", walk: "Promenad", sleep: "Sova", car: "Bil" },
  log: { title: "Vad hände?", editTitle: "Redigera logg", subtitle: "Välj en händelse för varje sak – kiss och bajs kan sparas tillsammans.", pee: "Kiss", poo: "Bajs", outside: "Ute", inside: "Inne", nothing: "Inget ännu", time: "När hände det?", timePlaceholder: "Välj datum och tid", dateTimeHeader: "Datum / tid", activity: "Aktivitet", notes: "Anteckning (valfritt)", photo: "Foto (valfritt)", attachPhoto: "Lägg till foto", attachPhotoBody: "Välj ett nytt foto eller ett från bildbiblioteket.", takePhoto: "Ta foto", choosePhoto: "Välj från bilder", removePhoto: "Ta bort foto", changePhoto: "Byt foto", photoHint: "Lägg till ett foto som minne från den här loggen.", photoAdding: "Lägger till…", photoPermission: "Kameran eller bildbiblioteket är inte tillgängligt. Aktivera åtkomst i Inställningar.", photoError: "Fotot kunde inte läggas till. Försök igen.", saved: "Sparat", saveError: "Loggen kunde inte sparas. Försök igen.", accident: "Det händer. Vi provar lite tidigare nästa gång.", pooSaved: "Sparat. Det hjälper oss se mönstret.", followUp: "Prova en lugn kissrunda om 15 minuter.", history: "Logg", hint: "Tryck på en rad för att redigera. Håll in för fler alternativ.", emptyTitle: "Loggen börjar med en liten stund ute", emptyBody: "Spara kiss, bajs eller Inget ännu så lär sig förslagen er vardag.", deleteConfirm: "Ta bort den här händelsen?", deleteAction: "Ta bort" },
  learn: { title: "Små steg, stor skillnad", subtitle: "Korta, granskade övningar när ni behöver dem.", reviewed: "Granskad", minutes: "min", start: "Börja", practice: "Öva igen", video: "Kort video", search: "Sök efter ett problem", searchPlaceholder: "rumsrenhet, koppel, vila", exercisesCount: "{{count}} övningar", stepsTitle: "Gör så här", draft: "Utkast", noResults: "Inget hittades ännu.", filters: "Snabbfilter", filterAll: "Alla", filterCurrent: "För min ålder", filterStart: "Start & hem", filterToilet: "Rumsrenhet", filterSocial: "Socialisering", filterCalm: "Lugn & hantering", filterMovement: "Koppel & inkallning", sortRecommended: "Rekommenderade", sortShortest: "Kortast först", listView: "Lista", grid2: "2 kolumner", grid3: "3 kolumner" },
  journey: { title: "Lunas resa", subtitle: "Spara de små ögonblicken som blir stora minnen.", growthTitle: "växer varje dag", growthBody: "Milstolparna är till för minnen, inte prestation.", milestones: "Milstolpar", add: "Lägg till milstolpe", edit: "Redigera milstolpe", empty: "Din tidslinje börjar här.", emptyBody: "Lägg till hemkomst, första kursen eller något ni vill minnas.", addPrompt: "Vad vill du minnas?", description: "Beskrivning (valfritt)", date: "Datum", photo: "Foto (valfritt)", attachPhoto: "Lägg till foto", photoHint: "Lägg till ett foto från minnet.", custom: "Egen milstolpe", saveError: "Milstolpen kunde inte sparas. Försök igen." },
  profile: { title: "Tryggt för hela familjen", dogs: "Hundar", addDog: "Lägg till hund", editDog: "Redigera hund", addFirstDog: "Lägg till din första hund", settings: "Inställningar", language: "Språk", reminders: "Påminnelser", quiet: "Tysta timmar", quietStart: "start", quietEnd: "slut", support: "Hjälp och support", privacy: "Integritet", export: "Exportera min data", delete: "Radera lokal data", local: "Lokal data", localBody: "Du behöver inget konto för att komma igång. Dina loggar sparas på den här enheten.", swedish: "Svenska", notificationOn: "Påminnelser är aktiverade", notificationOff: "Påminnelser är avstängda", noDog: "Lägg till din första hund", noDogBody: "En liten profil räcker för att börja.", deleteConfirm: "Detta raderar hundprofiler, loggar, milstolpar, lokala media och väntande notiser från den här enheten.", deleteAction: "Radera", exportError: "Export kunde inte startas", localeHint: "Fullt granskade språk släpps stegvis. Språkväljaren och kärnflödet är förberedda från dag ett.", supportHint: "Support ska vara åtkomligt i appen · Ingen annonsering eller beteendeförsäljning.", holdToEdit: "Håll in en hund för att redigera detaljer.", preparation: "Förberedelser inför hämtning", preparationHint: "Bocka av sådant som är klart före valpen kommer hem." },
  reason: { age_baseline: "Åldersanpassad starttid", after_wake: "Efter vila", after_meal: "Efter mat eller vatten", after_play: "Efter lek eller träning", recent_pee_accident: "Lite tidigare efter en olycka", bowel_pattern: "Mönster efter mat och morgon", manual: "Manuell justering", follow_up: "Följ upp en lugn runda" },
  dog: { name: "Hundens namn", breed: "Ras eller blandras", sex: "Kön", female: "Tik", male: "Hane", unknown: "Blandras/okänd", birth: "Födelsedatum (ungefär går bra)", arrival: "Kom hem", weight: "Vikt (kg)", chip: "Chipnummer", allergies: "Allergier eller känslighet", photo: "Foto", addPhoto: "Lägg till foto", changePhoto: "Byt foto", birthPlaceholder: "Välj födelsedatum", added: "Hund tillagd", limit: "Version 1 stöder två hundar på den här enheten.", saveError: "Hundprofilen kunde inte sparas. Försök igen." },
  prep: { safe_space: "Trygg plats", food: "Aktuellt foder", bowls: "Mat- och vattenskålar", toilet: "Toalettutrustning", harness: "Sele och ID-bricka", chews: "Tugg och leksaker", car: "Resan hem", vet: "Boka veterinär", household: "Kom överens hemma" },
  notifications: { title: "Påminnelser när ni behöver dem", body: "Puppysteps räknar ut nästa förslag lokalt på telefonen. Leverans beror på iOS inställningar.", allow: "Visa min första påminnelse", later: "Inte nu", disabled: "Notiser är inte tillåtna. Du kan aktivera dem i Inställningar.", reminderTitle: "Dags att kolla {{name}}", reminderBody: "Behöver ni gå ut? Tryck för att logga." },
  onboarding: { title: "Börja med er hund", body: "En liten profil räcker. Du kan komplettera och ändra allt senare.", start: "Skapa hundprofil" },
};

const en = {
  ...sv,
  nav: { today: "Today", log: "Log", learn: "Learn", journey: "Journey", profile: "Profile" },
  common: { ...sv.common, save: "Save", cancel: "Cancel", close: "Close", add: "Add", done: "Done", undo: "Undo", now: "Now", outside: "Outside", inside: "Inside", nothing: "Nothing yet", today: "Today", allDogs: "All dogs", on: "On", off: "Off", select: "Select" },
  today: { ...sv.today, eyebrow: "A calmer day with", next: "Next suggestion", inAbout: "in about", reminderOnBody: "Puppysteps will show the next calm suggestion when it is useful.", reason: "Why now?", log: "Quick log", routine: "Routine", routineSaved: "{{activity}} saved", saveError: "That could not be saved. Please try again.", wake: "Woke up", meal: "Eat", play: "Play", walk: "Walk", drink: "Drink", sleep: "Sleep", ageMonths: "{{count}} months old", noReminder: "No reminder yet", noReminderBody: "Turn reminders on when you are ready — you can change this any time.", enable: "Show my routine", agenda: "Today's dogs", last: "Recent events", responsible: "I am responsible now", away: "I am not responsible right now", age: "Age-based starting time", tip: "Reward calmly outside.", subtle: "Follow the next small step and let accidents stay neutral." },
  weather: { ...sv.weather, title: "Walk weather today", loading: "Getting the weather…", unavailable: "Weather is waiting", refresh: "Refresh", now: "Now", good: "Good for a walk", short: "Short walk", wait: "Wait a little", clear: "Clear", mostlyClear: "Mostly clear", cloudy: "Cloudy", foggy: "Foggy", rainy: "Rainy", snowy: "Snowy", showers: "Showers", snowShowers: "Snow showers", thunderstorms: "Thunderstorms", permission: "Allow location access for local weather.", error: "We could not get the weather. Try again.", source: "Weather data by Open-Meteo" },
  routine: { wake: "Wake", meal: "Eat", drink: "Drink", play: "Play", walk: "Walk", sleep: "Sleep", car: "Car" },
  log: { ...sv.log, title: "What happened?", editTitle: "Edit log", subtitle: "Choose one outcome for each function — pee and poo can be saved together.", pee: "Pee", poo: "Poo", outside: "Outside", inside: "Inside", nothing: "Nothing yet", time: "When did it happen?", timePlaceholder: "Choose date and time", dateTimeHeader: "Date / Time", activity: "Activity", notes: "Note (optional)", photo: "Photo (optional)", attachPhoto: "Add photo", attachPhotoBody: "Choose a new photo or one from your photo library.", takePhoto: "Take photo", choosePhoto: "Choose from photos", removePhoto: "Remove photo", changePhoto: "Change photo", photoHint: "Attach a photo memory to this log.", photoAdding: "Adding…", photoPermission: "Camera or photo access is unavailable. Enable access in Settings.", photoError: "The photo could not be added. Please try again.", saved: "Saved", saveError: "The log could not be saved. Please try again.", accident: "It happens. We will try a little earlier next time.", pooSaved: "Saved. This helps us see the pattern.", followUp: "Try a calm pee trip in 15 minutes.", history: "Log", hint: "Tap a row to edit it. Hold a row for more options.", emptyTitle: "Your log starts with a small trip outside", emptyBody: "Save pee, poo, or Nothing yet so suggestions learn your day.", deleteConfirm: "Remove this event?", deleteAction: "Remove" },
  learn: { ...sv.learn, title: "Small steps, big difference", subtitle: "Short, reviewed exercises when you need them.", reviewed: "Reviewed", minutes: "min", start: "Start", practice: "Practice again", video: "Short video", search: "Search for a problem", searchPlaceholder: "house training, leash, rest", exercisesCount: "{{count}} exercises", stepsTitle: "Try this", draft: "Draft", noResults: "Nothing found yet.", filters: "Quick filters", filterAll: "All", filterCurrent: "For my age", filterStart: "Start & home", filterToilet: "Toilet", filterSocial: "Socialisation", filterCalm: "Calm & handling", filterMovement: "Leash & recall", sortRecommended: "Recommended", sortShortest: "Shortest first", listView: "List", grid2: "2 columns", grid3: "3 columns" },
  journey: { ...sv.journey, title: "Your puppy's journey", subtitle: "Keep the small moments that become big memories.", growthTitle: "grows every day", growthBody: "Milestones are for memories, not performance.", milestones: "Milestones", add: "Add milestone", edit: "Edit milestone", empty: "Your timeline starts here.", emptyBody: "Add coming home, a first class, or something you want to remember.", addPrompt: "What do you want to remember?", description: "Description (optional)", date: "Date", photo: "Photo (optional)", attachPhoto: "Add photo", photoHint: "Add a photo from this memory.", custom: "Custom milestone", saveError: "The milestone could not be saved. Please try again." },
  profile: { ...sv.profile, title: "Safe for the whole household", dogs: "Dogs", addDog: "Add dog", editDog: "Edit dog", addFirstDog: "Add your first dog", settings: "Settings", language: "Language", reminders: "Reminders", quiet: "Quiet hours", quietStart: "start", quietEnd: "end", support: "Help and support", privacy: "Privacy", export: "Export my data", delete: "Delete local data", local: "Local data", localBody: "You do not need an account to get started. Your logs are stored on this device.", swedish: "Swedish", notificationOn: "Reminders are on", notificationOff: "Reminders are off", noDog: "Add your first dog", noDogBody: "A small profile is enough to begin.", deleteConfirm: "This deletes dog profiles, logs, milestones, local media, and pending reminders from this device.", deleteAction: "Delete", exportError: "Export could not start", localeHint: "Fully reviewed languages are released in stages. The selector and core flow are prepared from day one.", supportHint: "Support should be available in the app · No advertising or behavioral data sales.", holdToEdit: "Hold a dog to edit details.", preparation: "Prepare before pick-up", preparationHint: "Check off each item before your puppy comes home." },
  reason: { ...sv.reason, age_baseline: "Age-based starting time", after_wake: "After rest", after_meal: "After food or water", after_play: "After play or training", recent_pee_accident: "A little earlier after an accident", bowel_pattern: "Pattern after food and morning", manual: "Manual adjustment", follow_up: "Follow up a calm trip" },
  dog: { ...sv.dog, name: "Dog's name", breed: "Breed or mix", sex: "Sex", female: "Female", male: "Male", unknown: "Mixed/unknown", birth: "Birth date (estimate is fine)", arrival: "Came home", weight: "Weight (kg)", chip: "Microchip number", allergies: "Allergies or sensitivities", photo: "Photo", addPhoto: "Add photo", changePhoto: "Change photo", birthPlaceholder: "Choose birth date", added: "Dog added", limit: "Version 1 supports two dogs on this device.", saveError: "The dog profile could not be saved. Please try again." },
  prep: { safe_space: "Quiet safe space", food: "Current food", bowls: "Food and water bowls", toilet: "Toilet supplies", harness: "Harness and ID tag", chews: "Chews and toys", car: "Journey home", vet: "Book a vet appointment", household: "Agree household routines" },
  notifications: { ...sv.notifications, title: "Reminders when you need them", body: "Puppysteps calculates the next suggestion locally on your phone. Delivery depends on iOS settings.", allow: "Show my first reminder", later: "Not now", disabled: "Notifications are not allowed. You can enable them in Settings.", reminderTitle: "Time to check on {{name}}", reminderBody: "Do you need a toilet trip? Tap to log it." },
  onboarding: { ...sv.onboarding, title: "Start with your dog", body: "A small profile is enough. You can complete and change everything later.", start: "Create dog profile" },
};

const smallLocale = (label: string) => ({
  ...en,
  nav: { today: label === "fr" ? "Aujourd’hui" : label === "de" ? "Heute" : label === "da" ? "I dag" : label === "fi" ? "Tänään" : "I dag", log: label === "fr" ? "Journal" : label === "de" ? "Logbuch" : label === "fi" ? "Loki" : "Log", learn: label === "fr" ? "Apprendre" : label === "de" ? "Trainieren" : label === "da" ? "Træn" : label === "fi" ? "Harjoittele" : "Tren", journey: label === "fr" ? "Parcours" : label === "de" ? "Reise" : label === "da" ? "Rejse" : label === "fi" ? "Matka" : "Reise", profile: label === "fr" ? "Profil" : label === "de" ? "Profil" : label === "da" ? "Profil" : label === "fi" ? "Profiili" : "Profil" },
});

const resources = {
  "sv-SE": { translation: sv },
  "en-GB": { translation: en },
  "fr-FR": { translation: smallLocale("fr") },
  "de-DE": { translation: smallLocale("de") },
  "da-DK": { translation: smallLocale("da") },
  "fi-FI": { translation: smallLocale("fi") },
  "nb-NO": { translation: smallLocale("nb") },
};

const supported: Locale[] = ["sv-SE", "en-GB", "fr-FR", "de-DE", "da-DK", "fi-FI", "nb-NO"];
const initialLocale: Locale = "en-GB";

// i18next exposes `use` on its default instance; this is the documented setup API.
// eslint-disable-next-line import/no-named-as-default-member
void i18n.use(initReactI18next).init({ resources, lng: initialLocale, fallbackLng: "en-GB", interpolation: { escapeValue: false }, returnNull: false });

export { i18n, supported };
