import type { ImageSourcePropType } from "react-native";
import type { Lesson } from "../domain/models";

export type LessonContent = Lesson & {
  ageGuide: string;
  goal: string;
  thumbnail: ImageSourcePropType;
  whenToStop: string;
};

const thumbnails = {
  settling: require("../../assets/lessons/settling-home.jpg"),
  reward: require("../../assets/lessons/reward-contact.jpg"),
  toilet: require("../../assets/lessons/toilet-routine.jpg"),
  handling: require("../../assets/lessons/calm-handling.jpg"),
  leash: require("../../assets/lessons/loose-leash.jpg"),
  social: require("../../assets/lessons/socialisation.jpg"),
};

/**
 * Beta content is deliberately English-only until every locale has completed
 * native-language and subject-matter review. UI chrome can still be translated.
 */
export const LESSONS: LessonContent[] = [
  {
    id: "lesson_first_days",
    title: "The first days at home",
    summary: "Make the new home quiet, predictable, and easy to understand.",
    goal: "Your puppy can eat, sleep, explore, and approach you without pressure.",
    ageGuide: "Start here",
    duration: "4",
    steps: [
      "Prepare one quiet bed, water, and a nearby toilet route before the puppy arrives.",
      "Keep the first days small: familiar people, short explorations, and plenty of undisturbed rest.",
      "Offer a toilet trip after waking, eating, drinking, and play; reward success outside.",
      "Let contact be voluntary. Sit nearby, reward check-ins, and avoid passing the puppy around.",
    ],
    tags: ["start", "home", "sleep", "settling"],
    status: "draft",
    thumbnail: thumbnails.settling,
    whenToStop: "Pause and make the environment quieter if your puppy hides, freezes, or cannot settle.",
  },
  {
    id: "lesson_reward",
    title: "Rewards and timing",
    summary: "Show your puppy exactly which small choice worked.",
    goal: "A calm marker predicts a reward without pressure or confusion.",
    ageGuide: "From day one",
    duration: "3",
    steps: [
      "Choose a short marker such as “yes”. Say it once, then give a tiny treat.",
      "Practise five marker-and-treat repetitions when nothing else is happening.",
      "Mark the exact moment your puppy does something useful, such as looking at you or keeping four paws down.",
      "Deliver the reward within a second, then pause. Three good repetitions are enough.",
    ],
    tags: ["basics", "reward", "timing"],
    status: "draft",
    thumbnail: thumbnails.reward,
    whenToStop: "Stop while your puppy still wants more, or sooner if they turn away or stop taking food.",
  },
  {
    id: "lesson_name",
    title: "Name and voluntary check-ins",
    summary: "Build an easy first conversation with your puppy.",
    goal: "Your puppy turns towards you after hearing their name once.",
    ageGuide: "8+ weeks",
    duration: "3",
    steps: [
      "Begin in a quiet room while your puppy is awake and relaxed.",
      "Say the name once. Wait silently for a glance rather than repeating it.",
      "Mark the glance and place a treat close to you.",
      "After three repetitions, move one step and let your puppy choose to check in again.",
    ],
    tags: ["name", "attention", "communication"],
    status: "draft",
    thumbnail: thumbnails.reward,
    whenToStop: "Make it easier if your puppy does not respond; distance and distraction matter more than repetition.",
  },
  {
    id: "lesson_toilet",
    title: "A simple toilet routine",
    summary: "Prevent accidents with timing, supervision, and calm rewards.",
    goal: "Your puppy gets frequent chances to succeed in the right place.",
    ageGuide: "8+ weeks",
    duration: "4",
    steps: [
      "Go out promptly after sleep, food, water, energetic play, and whenever your puppy becomes restless.",
      "Use the same quiet area and wait without playing or distracting them.",
      "Reward calmly as soon as they finish outside, then allow a little sniffing time.",
      "Clean indoor accidents without comment. Log the time and try slightly earlier next time.",
    ],
    tags: ["toilet", "pee", "poo", "routine"],
    status: "draft",
    thumbnail: thumbnails.toilet,
    whenToStop: "Contact a veterinarian for sudden changes, straining, pain, blood, vomiting, diarrhoea, or unusual thirst.",
  },
  {
    id: "lesson_signals",
    title: "Read early toilet signals",
    summary: "Spot the small changes that often happen before an accident.",
    goal: "You notice your puppy’s own pattern and act before urgency builds.",
    ageGuide: "8+ weeks",
    duration: "3",
    steps: [
      "Watch for sudden sniffing, circling, wandering away, restlessness, or moving towards an exit.",
      "When you see a possible signal, go outside calmly rather than asking for extra cues.",
      "Log both successes and “nothing yet” trips so the pattern stays honest.",
      "Review the previous two days and adjust the routine one small step at a time.",
    ],
    tags: ["toilet", "signals", "log", "routine"],
    status: "draft",
    thumbnail: thumbnails.toilet,
    whenToStop: "Do not delay a trip to test a theory; young puppies need more frequent opportunities than adult dogs.",
  },
  {
    id: "lesson_handling",
    title: "Calm cooperative handling",
    summary: "Prepare for paws, grooming, and vet care without restraint battles.",
    goal: "Brief touch predicts something pleasant and your puppy can opt out.",
    ageGuide: "8+ weeks",
    duration: "4",
    steps: [
      "Start when your puppy is relaxed. Touch the shoulder for one second, then reward.",
      "Progress gradually towards legs, paws, ears, collar, and mouth over several sessions.",
      "Keep your grip soft and release before your puppy pulls away.",
      "Add tools such as a brush or nail clipper only after simple touch feels easy.",
    ],
    tags: ["handling", "paws", "grooming", "vet"],
    status: "draft",
    thumbnail: thumbnails.handling,
    whenToStop: "Stop at tension, repeated turning away, lip licking, freezing, growling, or attempts to escape.",
  },
  {
    id: "lesson_recall",
    title: "Recall foundations",
    summary: "Make returning to you safe, easy, and worthwhile.",
    goal: "Your puppy happily follows you in a low-distraction place.",
    ageGuide: "8+ weeks",
    duration: "4",
    steps: [
      "Begin indoors or in a secure, quiet area when your puppy is already looking your way.",
      "Say the recall cue once, move backwards, and warmly encourage them to follow.",
      "Reward close to your body, briefly touch the collar, then release the puppy back to something enjoyable.",
      "Outside secure areas, use a harness and long line until recall is reliable around distractions.",
    ],
    tags: ["recall", "outdoors", "safety"],
    status: "draft",
    thumbnail: thumbnails.reward,
    whenToStop: "Lower the distraction rather than repeating the cue. Never punish your puppy after they return.",
  },
  {
    id: "lesson_leash",
    title: "Loose-leash first steps",
    summary: "Reward slack in the lead before distance matters.",
    goal: "Your puppy can take a few connected steps without pulling.",
    ageGuide: "10+ weeks",
    duration: "4",
    steps: [
      "Let your puppy investigate the harness and lead indoors, pairing each with treats.",
      "Reward a glance towards you while the lead hangs loose.",
      "Take one or two steps, mark the loose lead, and reward beside your leg.",
      "If the lead tightens, pause or create more distance. Continue when it is loose again.",
    ],
    tags: ["leash", "walk", "outdoors"],
    status: "draft",
    thumbnail: thumbnails.leash,
    whenToStop: "End after a few successful steps, or earlier if your puppy is tired, worried, or overstimulated.",
  },
  {
    id: "lesson_biting",
    title: "Puppy biting and safe chewing",
    summary: "Meet the need to chew while protecting hands and household items.",
    goal: "Your puppy can switch from skin or clothing to an appropriate chew.",
    ageGuide: "8 weeks–7 months",
    duration: "4",
    steps: [
      "Keep several puppy-safe chews and toys within reach before play begins.",
      "If teeth touch skin or clothing, become still and calmly offer a suitable toy once.",
      "If biting continues, step away for a brief, boring pause; return when everyone is calm.",
      "Check the basics: many intense biting spells follow tiredness, hunger, or overexciting play.",
    ],
    tags: ["biting", "chewing", "teething", "play"],
    status: "draft",
    thumbnail: thumbnails.handling,
    whenToStop: "Ask a veterinarian about mouth pain or broken teeth, and seek qualified behaviour help for persistent fearful or aggressive biting.",
  },
  {
    id: "lesson_rest",
    title: "A voluntary safe resting place",
    summary: "Teach settling on an open bed or mat without confinement pressure.",
    goal: "Your puppy chooses the resting place and can leave freely.",
    ageGuide: "From day one",
    duration: "3",
    steps: [
      "Place an open bed or mat in a quiet area where the puppy can still see the household.",
      "Drop a treat on the bed, then let your puppy leave; do not hold them there.",
      "Quietly reward sitting, lying down, or relaxing on the bed during normal life.",
      "Protect the space from children and visitors whenever the puppy is resting.",
    ],
    tags: ["rest", "sleep", "home", "settle"],
    status: "draft",
    thumbnail: thumbnails.settling,
    whenToStop: "In Sweden, closed crates are generally not home resting places. Check current rules and use an open, safe setup.",
  },
  {
    id: "lesson_alone",
    title: "Alone training in seconds",
    summary: "Build comfortable distance only after your puppy feels safe at home.",
    goal: "A tiny separation remains calm and uneventful.",
    ageGuide: "Once settled",
    duration: "4",
    steps: [
      "Start while your puppy is relaxed and occupied in a familiar safe area.",
      "Take one step away or disappear for one second, then return before concern appears.",
      "Repeat two or three easy trials, mixing in trials where you do not leave.",
      "Increase only one thing at a time—distance or duration—and keep most repetitions easy.",
    ],
    tags: ["alone", "home", "settle", "independence"],
    status: "draft",
    thumbnail: thumbnails.settling,
    whenToStop: "Return to an easier step after vocalising, pacing, scratching, panting, or refusing food. Seek help for ongoing distress.",
  },
  {
    id: "lesson_social",
    title: "Calm socialisation",
    summary: "Help your puppy observe the world without being pushed into it.",
    goal: "New sights, sounds, people, and suitable dogs remain manageable.",
    ageGuide: "Especially 8–16 weeks",
    duration: "5",
    steps: [
      "Choose one low-intensity experience while your puppy is rested—for example a bicycle at a distance.",
      "Let your puppy watch, sniff, or move away. Reward calm observation and voluntary approach.",
      "Keep greetings brief and selective; your puppy does not need to meet everyone.",
      "Leave while it is still going well and give your puppy quiet recovery time afterwards.",
    ],
    tags: ["socialisation", "environment", "people", "dogs"],
    status: "draft",
    thumbnail: thumbnails.social,
    whenToStop: "Increase distance if your puppy freezes, hides, lunges, or cannot eat. Ask your veterinarian which environments are safe during vaccination.",
  },
];
